package constant;

public interface Constants {
    int CONSTANT_LOGIN = 1;
    int CONSTANT_REGISTER = 2;
    int CONSTANT_CANCEL = 3;

    int CONSTANT_CUSTOMER = 1;
    int CONSTANT_EMPLOYEE = 2;

    int CONSTANT_FINANCE = 1;
    int CONSTANT_SALES_AND_MARKETING = 2;
    int CONSTANT_LEGAL = 3;
    int CONSTANT_INFORMATION_TECHNOLOGY = 4;
    int CONSTANT_HUMAN_RESOURCES = 5;
    int CONSTANT_HOUSE_KEEPING = 6;
    int CONSTANT_SECURITY = 7;
    int CONSTANT_CUSTOMER_SERVICE = 8;

    int CONSTANT_HEAD_OF_THE_DEPARTMENT = 1;
    int CONSTANT_STAFF = 2;

    int CONSTANT_EDIT_BASIC_INFORMATION = 1;
    int CONSTANT_SEARCH_USER = 2;


    int SEARCH_BY_USERNAME = 1;
    int SEARCH_BY_FULL_NAME = 2;
    int SEARCH_BY_EMAIL = 3;
    int SEARCH_BY_DEPARTMENT = 4;
    int SEARCH_BY_RESIDENCY = 5;
    int CONSTANT_CANCEL_1 = 6;

    int CONSTANT_SEARCH_RESIDENCY_INFORMATION = 2;
}
